@startuml sample

|Actor 1|

start
:todo 1;

|Actor 2|

if (todo 2) then (yes)
  :todo 2;
elseif (todo 3) then (yes)
  :Text 3;
else (no)
  :no;
  stop
endif

|Actor 1|

fork
  :fork 1;
fork again
  :fork 2;
end fork

stop

@enduml