@startuml contoh

left to right direction
skinparam packageStyle rectangle

actor "Admin" as acadmin
actor "Customer" as accustomer

rectangle "Penyewaan" {

    usecase "Melihat ketersediaan kendaraan" as todo1
    usecase "Mendaftar & Menyewa" as todo2
    usecase "Mencetak Kontrak" as todo3
    usecase "Pembayaran DP" as todo4
    usecase "Serah Terima Kendaraan" as todo5
    usecase "Perpanjangan Sewa" as todo6
    usecase "Pengembalian Kendaraan" as todo7
    usecase "Pelunasan" as todo8
    usecase "Melihat Laporan Omset" as todo9

    todo1 -- accustomer
    acadmin -- todo2
    todo2 -- accustomer
    acadmin -- todo6
    todo6 -- accustomer
    acadmin -- todo7
    todo7 -- accustomer
    acadmin -- todo9

    todo2 .> todo1 : exclude
    todo3 <. todo2 : include
    todo4 <. todo3 : include
    todo5 <. todo4 : include
    todo6 .> todo5 : exclude
    ' todo7 <. todo5 : include
    todo7 <. todo6 : include
    todo8 <. todo7 : include

}

@enduml